### ISSUE TITLE
Can't get it working in Quasar Framework

### ISSUE THREAD

**Issue by Dylan190774** [likemusic/vue-template-extends#2]
I'm trying to install the loader in Quasar Framework, but so far without success.

I put this in quasar.conf.js:
```
    extendWebpack (cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.vue$/,
          resourceQuery: /blockType=template-extends/,
          loader: ['vue-template-extends'],
          exclude: /node_modules/
        });
     }
```

The loader seems to be installed correctly, but I get the error:

``extends` block must contain only `slot` nodes! Given: TEMPLATE-EXTENDS`

I tried this with just the examples in the readme, so I can't see what I'm doing wrong.

Since Quasar is one of the most used Vue frameworks, it would be nice to get this working.
Any ideas?

**Comment by likemusic** [comment]
@Dylan190774 Are you using Vue.js v2? If yes, then keep only `resourceQuery` and `loader` keys in your config object, like it's described in `README.md`. You don't need here `enforce`, `test`, `exclude` keys and you must delete them.

**Comment by Dylan190774** [comment]
Thanks for your reply. 
That seems to help a little bit. The app compiles now, but when I run it in the browser I now get the following error in console:

```
vue-router.esm.js?8c4f:2128 ReferenceError: Vue is not defined
    at eval (bindRenders.js?8d07:2)
    at eval (child.vue?c961:7)
    at eval (child.vue?7e09:21)
    at Module../src/pages/main.vue (24.js:35)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
```

When I replace the template-extends part with just a normal template, it renders ok, so it must be the template-extends where it goes wrong, but I can't find why, since I just copied your base en child templates to try it out.

**Comment by likemusic** [comment]
@Dylan190774 Your new error produced by loader's bug.
I made new branch that should fix this error in branch `issue-2-vue-not-found-in-bind-renders`.

Please, try install loader from this branch (run `npm install --save likemusic/vue-template-extends#issue-2-vue-not-found-in-bind-renders`) and let me know about the result.

**Comment by Dylan190774** [comment]
I appreciate your effort! Too bad, I get another error now...

TypeError: vue__WEBPACK_IMPORTED_MODULE_0__.default.compile is not a function
    at eval (bindRenders.js?8d07:4)
    at eval (child.vue?9cf0:7)
    at eval (child.vue?7e09:21)
    at Module../src/pages/main.vue (18.js:95)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)

**Comment by likemusic** [comment]
@Dylan190774 My mistake. I updated the branch. Please try again run `npm install --save likemusic/vue-template-extends#issue-2-vue-not-found-in-bind-renders` or `npm update`.

**Comment by Dylan190774** [comment]
I still get the error. How do I know I have the latest version of the branch?

**Comment by likemusic** [comment]
@Dylan190774 Seems that I need to create some Quasar Framework app by myself to fix it. I'll try it on weekend.

> How do I know I have the latest version of the branch?

Look at `node_modules/vue-template-extends/bindRenders.js`. If there is `import Vue from 'vue/dist/vue.min.js';` in the first line then you have updated branch.

**Comment by Dylan190774** [comment]
Hmm, there is only this: 
`import Vue from 'vue';
`
I did 
`yarn upgrade likemusic/vue-template-extends#issue-2-vue-not-found-in-bind-renders`

to update the package. I'm no npm, yarn or git expert, so I don't really know what I'm doing.

**Comment by Dylan190774** [comment]
Yes it's working now! Thanks a lot.
I had to change the file manually though, since the yarn upgrade command did not make the change (yet?).
Maybe some issue with github servers?

**Comment by likemusic** [comment]
@Dylan190774  I'm sorry. I forgot commit last changes before push.
Also I have no effect, before I run 
`yarn add likemusic/vue-template-extends#issue-2-vue-not-found-in-bind-renders`.

**Comment by likemusic** [comment]
I merged `issue-2-vue-not-found-in-bind-renders`-branch into `main`-branch and publish it on npm.

You could switch to it by running `yarn add vue-template-extends`.

**Comment by Dylan190774** [comment]
Great, I'll test the loader a bit further this week.
I also tried vue-inheritance-loader.  
Are there any things this loader does different (or even better?) than yours? My main concern with it was that hot reload didn't seem to be triggered when the base template changes.

**Comment by Dylan190774** [comment]
Oops, hot reload is not working ok.
When I change the child template, the page is refreshed but has the same content.
And when the base template is changed, the child template is ignored completely, so only the base template is shown.

**Comment by likemusic** [comment]
@Dylan190774 
> Are there any things this loader does different (or even better?) than yours?

I looked at `vue-inheritance-loader` implementation. It replaces default vue-loader and generate real template-block for component.
`Vue-template-extends` doesn't replace default vue-loader, therefore it doesn't generate template-block, but create render-functions and add them to component options.

Also syntax based on vue-native slot-tags used in `vue-template-extends`, allows you extend third-party component's template, that is impossible by `vue-inheritance-loader`.

**Comment by likemusic** [comment]
@Dylan190774 
> Oops, hot reload is not working ok.

I don't use hot-reloads on my current projects, but I think that is should be possible to fix. I'll try to fix this on weekends.

**Comment by Dylan190774** [comment]
Well, part of the problem may be in vue-hot-reload-api itself.
I did an 'extends' in the child component to inherit some variables from the base component.
See this issue:  [](https://github.com/vuejs/vue-hot-reload-api/issues/68)
Guess I'll have to learn to refresh the whole page when making a change.
